# Generated by Django 4.0.3 on 2022-03-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemanager', '0002_remove_customer_id_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
