# Generated by Django 4.0.3 on 2022-03-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemanager', '0003_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
    ]
