# Generated by Django 4.0.3 on 2022-03-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemanager', '0004_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
